// SPDX-License-Identifier: MIT
'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const { renderTemplate } = require('../../src/lib/scaffold.js');

const TPL = path.join(__dirname, '..', '..', 'src', 'templates', 'husky', 'pre-push.eta');

test('husky pre-push template renders advisory comment', () => {
	const rendered = renderTemplate(TPL, {});
	assert.match(rendered, /Generated by KernDX pipeline/);
});

test('husky pre-push template calls preflight', () => {
	const rendered = renderTemplate(TPL, {});
	assert.match(rendered, /\.\/\.kerndx-pipeline\/bin\/kerndx preflight/);
});

test('husky pre-push template exits 0', () => {
	const rendered = renderTemplate(TPL, {});
	assert.match(rendered, /exit 0/);
});

test('husky pre-push template has sh shebang', () => {
	const rendered = renderTemplate(TPL, {});
	assert.match(rendered, /^#!\/usr\/bin\/env sh/);
});
