// SPDX-License-Identifier: BUSL-1.1
import {defineConfig} from 'vitepress';
import {withMermaid} from 'vitepress-plugin-mermaid';
import sidebar from './sidebar.generated.mjs';
import {repoUrl} from '../scripts/repo.mjs';
import {seoHeadEntries} from '../scripts/seo-head.mjs';
import githubLight from 'shiki/themes/github-light.mjs';
import githubDark from 'shiki/themes/github-dark.mjs';
import responsiveTables from './theme/responsive-tables.mjs';
import {readFileSync} from 'node:fs';
import {applyLastmod} from '../scripts/sitemap-lastmod.mjs';

const HOSTNAME = 'https://docs.jvb-consulting.io';
const BASE = process.env.DOCS_BASE || '/';
// A frozen version tree (DOCS_BASE=/X.Y/ DOCS_FROZEN=1) is excluded from search indexing and
// the sitemap; its pages canonicalise to the live latest equivalent when one still exists.
const FROZEN = process.env.DOCS_FROZEN === '1';
// Smart canonical needs the latest tree's slug set. The version orchestrator writes the latest
// routes to LATEST_ROUTES_FILE before building frozen trees; when absent (a standalone frozen
// build), every frozen page self-canonicalises.
let LATEST_SLUGS = null;
if(FROZEN && process.env.LATEST_ROUTES_FILE)
{
	try
	{
		LATEST_SLUGS = new Set(JSON.parse(readFileSync(process.env.LATEST_ROUTES_FILE, 'utf8')));
	}
	catch
	{
		LATEST_SLUGS = null;
	}
}

// Per-page sitemap <lastmod> (git last-commit date of each page's source), generated by
// prepare.mjs into lastmod.generated.json before this config loads. Missing/empty → the
// sitemap simply omits <lastmod>; a uniform fabricated date is never emitted.
let LASTMOD_BY_SLUG = {};
try
{
	LASTMOD_BY_SLUG = JSON.parse(readFileSync(new URL('./lastmod.generated.json', import.meta.url), 'utf8'));
}
catch
{
	LASTMOD_BY_SLUG = {};
}

// ── Apex signature syntax colors ────────────────────────────────────────────
// VitePress emits per-token inline colors from the Shiki theme, so retuning the
// Apex scopes (method / type / modifier / parameter) can only be done in the theme
// itself — CSS cannot reach them. We extend the bundled GitHub themes with Apex-scope
// overrides so reference signatures read like Salesforce's docs: method names
// bronze-bold, types blue, modifiers red (no italic), parameters orange. Every other
// language keeps the stock GitHub palette. Scope aliases (the non-`.apex` forms) are
// defensive against grammar drift.
const APEX_LIGHT = {method: '#8a623c', type: '#1668d6', modifier: '#cf222e', param: '#953800'};
const APEX_DARK = {method: '#e0a064', type: '#79c0ff', modifier: '#ff7b72', param: '#ffa657'};

function apexScopeRules(p)
{
	return [
		{scope: ['entity.name.function.apex', 'entity.name.function'], settings: {foreground: p.method, fontStyle: 'bold'}},
		{scope: ['storage.type.apex', 'keyword.type.apex', 'entity.name.type.apex', 'support.class.apex', 'support.type.apex'], settings: {foreground: p.type}},
		{scope: ['storage.modifier.apex', 'storage.modifier'], settings: {foreground: p.modifier, fontStyle: ''}},
		{scope: ['entity.name.variable.parameter.apex', 'variable.parameter.apex', 'variable.parameter'], settings: {foreground: p.param}}
	];
}

// GitHub's bundled themes color code comments #6a737d in BOTH light and dark, which fails
// WCAG AA contrast on the code-block backgrounds (~3.7:1 on the dark surface). CSS cannot
// reach these tokens (VitePress emits per-token inline --shiki-light/--shiki-dark with no
// comment-specific selector), so override the comment scope at the theme-token level. The
// chosen hexes are GitHub's own fg.muted tokens — still muted, but >=4.5:1 on both surfaces.
// Appended AFTER the apex rules so they win, and orthogonal to the apex method/type/modifier/
// param scopes, which are untouched.
const commentRule = (foreground) => ({scope: ['comment', 'punctuation.definition.comment', 'string.comment'], settings: {foreground}});
// Raise the GitHub-light keyword red (#d73a49) that falls just under WCAG AA on the light code
// background to #cf222e — the same red already used for the Apex modifier scope, so the palette
// stays consistent. Light theme only; the dark theme already clears AA.
const recolorForeground = (tokenColors, swaps) => tokenColors.map((tc) =>
{
	const fg = tc.settings && tc.settings.foreground;
	const key = fg && fg.toLowerCase();
	return (key && swaps[key]) ? {...tc, settings: {...tc.settings, foreground: swaps[key]}} : tc;
});
const apexLightTheme = {...githubLight, name: 'kerndx-apex-light', tokenColors: [...recolorForeground(githubLight.tokenColors, {'#d73a49': '#cf222e'}), ...apexScopeRules(APEX_LIGHT), commentRule('#57606a')]};
const apexDarkTheme = {...githubDark, name: 'kerndx-apex-dark', tokenColors: [...githubDark.tokenColors, ...apexScopeRules(APEX_DARK), commentRule('#8b949e')]};

export default withMermaid(defineConfig({
	title: 'KernDX',
	description: 'A complete Salesforce Apex + LWC framework and library suite.',
	srcDir: 'src',
	lang: 'en-US',
	// '/' under the custom domain (mirror). A GitHub project-page deploy (e.g. the
	// ephemeral test repo) sets DOCS_BASE=/<repo>/ so assets resolve under the subpath.
	base: BASE,
	cleanUrls: true,
	ignoreDeadLinks: false,
	lastUpdated: true,
	sitemap: FROZEN ? undefined : {hostname: HOSTNAME, transformItems: (items) => applyLastmod(items, LASTMOD_BY_SLUG)},
	// Sitewide head: favicon (base-aware so it resolves on both the custom domain
	// and a /<repo>/ project-page deploy) + brand theme color + author.
	head: [
		['link', {rel: 'icon', type: 'image/svg+xml', href: `${BASE}favicon.svg`}],
		['meta', {name: 'theme-color', content: '#8a623c'}],
		['meta', {name: 'author', content: 'JVB Consulting'}]
	],
	themeConfig: {
		// F-shape top nav — most-important-first. "Why KernDX" leads (the evaluator's
		// first question), then the daily-driver paths, then lookup. Each tab lands on the
		// canonical first page of the matching sidebar section, so the top nav and the
		// left sidebar stay consistent. (The version selector lives in the sidebar.)
		nav: [
			{text: 'Why KernDX', link: '/'},
			{text: 'Get Started', link: '/installation'},
			{text: 'Fast Starts', link: '/fast-starts'},
			{text: 'Reference', link: '/reference/'}
		],
		search: {
			provider: 'local', options: {
				// The corpus is code-heavy (269 auto-generated Apex reference pages). Indexing
				// fenced code blocks pushed the local-search index well past the ~1 MB target, so
				// strip fenced code (and the noisy frontmatter) from the indexed content before
				// rendering. Prose, headings, and tables are still indexed; code is excluded.
				_render(src, env, md)
				{
					// Closing fence must use the same character as the opener AND be at least
					// as long (CommonMark). Capture the fence char (group 2) so the close is the
					// opener (\1) followed by zero-or-more of that same char (\2*) — length >=
					// opener. A bare \1 backreference (exact-length) leaves a block closed by a
					// longer fence unstripped, leaking code into the search index.
					const withoutCode = src
					.replace(/^---\n[\s\S]*?\n---\n/, '')
					.replace(/^ {0,3}(([`~])\2{2,})[\s\S]*?^ {0,3}\1\2*\s*$/gm, '');
					return md.render(withoutCode, env);
				}
			}
		}, sidebar, outline: {
			level: [
				2,
				3
			]
		}, socialLinks: [{icon: 'github', link: repoUrl()}]
	},
	markdown: {
		lineNumbers: false,
		// Custom Apex signature colors (see APEX_LIGHT/DARK above) + the responsive-table
		// plugin that labels each <td> for the mobile stacked-card layout.
		theme: {light: apexLightTheme, dark: apexDarkTheme},
		config(md)
		{
			md.use(responsiveTables);
		}
	}, // Canonical + Open Graph + Twitter card per page.
	transformPageData(pageData)
	{
		// Logical slug → self URL (base-aware: '/' for latest, '/X.Y/' for a frozen tree). For a
		// frozen page that still exists in latest, canonical points at the live latest URL;
		// otherwise it self-canonicalises. For the latest build BASE is '/', so selfUrl and
		// canonical both reduce to the historical `${HOSTNAME}/${slug}` — no change.
		const slug = pageData.relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '');
		const url = `${HOSTNAME}${BASE}${slug}`;
		// The home page (empty slug) always exists in latest at "/", but it is filtered out of
		// LATEST_SLUGS (which drops the empty slug), so treat it as present explicitly; otherwise
		// the frozen home would self-canonicalise instead of pointing at the latest home.
		const existsInLatest = slug === '' || (LATEST_SLUGS && LATEST_SLUGS.has(slug));
		const canonical = (FROZEN && existsInLatest) ? `${HOSTNAME}/${slug}` : url;
		// Resolved title: frontmatter title, else VitePress's H1-derived title. Guides carry
		// no frontmatter, so frontmatter.title is undefined for them — pageData.title is what
		// the <title> tag uses, and it is unique per page.
		const resolvedTitle = pageData.frontmatter.title || pageData.title;
		// The home page resolves to the bare site name "KernDX"; appending "| KernDX" (and,
		// below, the "{title} — KernDX, ..." description) would double it ("KernDX | KernDX",
		// "KernDX — KernDX, ..."). Special-case it to the plain site name + default description.
		const isHome = pageData.relativePath.replace(/(^|\/)index\.md$/, '$1') === '' || resolvedTitle === 'KernDX';
		const title = (!isHome && resolvedTitle) ? `${resolvedTitle} | KernDX` : 'KernDX';
		// Unique, non-empty <meta name="description"> per page. Without this, every page
		// lacking a frontmatter description inherits the site-wide default — a duplicate
		// meta-description SEO defect across 60+ pages. Two rules guarantee uniqueness:
		//   (1) no description → synthesize a title-based one (titles are unique);
		//   (2) reference (API) page WITH a description that doesn't already name its member
		//       → lead with the member name, so sibling classes (AndCondition / OrCondition)
		//         never share an identical description.
		// VitePress emits <meta name="description"> from pageData.description (top-level),
		// falling back to the site description — NOT from frontmatter.description. Setting
		// pageData.description is what actually overrides the per-page meta.
		const isReference = pageData.relativePath.startsWith('reference/');
		let desc = pageData.frontmatter.description;
		if (!desc)
		{
			desc = (resolvedTitle && !isHome)
				? `${resolvedTitle} — KernDX, a source-available Salesforce Apex and LWC framework.`
				: 'A complete Salesforce Apex + LWC framework and library suite.';
		}
		else if (isReference && resolvedTitle && !desc.includes(resolvedTitle))
		{
			desc = `${resolvedTitle} — ${desc}`;
		}
		pageData.description = desc;
		pageData.frontmatter.head ??= [];
		if(FROZEN)
		{
			pageData.frontmatter.head.push(['meta', {name: 'robots', content: 'noindex,follow'}]);
		}
		pageData.frontmatter.head.push([
			'link',
			{rel: 'canonical', href: canonical}
		], [
			'meta',
			{property: 'og:type', content: 'website'}
		], [
			'meta',
			{property: 'og:title', content: title}
		], [
			'meta',
			{property: 'og:description', content: desc}
		], [
			'meta',
			{property: 'og:url', content: url}
		], [
			'meta',
			{name: 'twitter:card', content: 'summary_large_image'}
		], [
			'meta',
			{name: 'twitter:title', content: title}
		], [
			'meta',
			{name: 'twitter:description', content: desc}
		]);
		// Social-share image (absolute https), OG site metadata, and schema.org
		// JSON-LD (Organization + WebSite sitewide, per-page TechArticle).
		pageData.frontmatter.head.push(...seoHeadEntries({title, description: desc, url, hostname: HOSTNAME, isHome}));
	},
	// withMermaid registers <Mermaid> globally, so mermaid's ~25 lazy diagram chunks + dagre +
	// katex land in the app chunk's dynamicImports and VitePress bakes a <link rel="modulepreload">
	// for each into EVERY page head — even though a ```mermaid fence appears on exactly one page and
	// no page on the critical path uses math. That eagerly pulls ~345 KB of unused JS on first paint
	// (the dominant cause of slow mobile FCP/LCP). The preload is only a fetch hint: the one diagram
	// page still renders because <Mermaid> dynamically imports its chunk at mount. Strip those hints
	// from the built HTML (the runtime import() path is untouched, so behaviour is unchanged). After
	// any mermaid/vitepress upgrade, rebuild and confirm only framework/theme/<page>.lean.js preloads
	// remain — a new eco chunk whose filename lacks these tokens would slip through.
	transformHtml(code)
	{
		return code.replace(
			/\n?[ \t]*<link rel="modulepreload" href="[^"]*\/assets\/chunks\/(?:katex|dagre|cytoscape|(?:virtual_)?mermaid|[a-z0-9-]*diagram[a-z0-9-]*|mindmap-definition|kanban-definition|timeline-definition)[^"]*">/gi,
			''
		);
	}
}));
