// SPDX-License-Identifier: BUSL-1.1
/**
 * @description Jest unit tests for the maskingExportModal LWC — the Export-package dialog built on
 *              lightning/modal (LightningModal). The base modal supplies the chrome + focus-trap; this
 *              dialog renders the export diff as a package-contents list grouped Add · Re-enable · Disable
 *              (each row carries a scope glyph, the field → rule, and a verb tag), a one-line change
 *              summary, an optional package-name chip, and two deploy paths: a live org-alias input that
 *              fills the Salesforce CLI command (Copy), and the zip download. Download resolves
 *              {action:'download'}; Cancel resolves null. It renders NO on-screen XML — the real zip is
 *              generated by the controller and downloaded by the caller. Verified via real DOM rendering
 *              with the global lightning/modal mock (whose close() is a shared jest.fn).
 *
 * @author Jason van Beukering
 * @date June 2026, July 2026
 */
import {createElement} from 'lwc';
import {mockClose} from 'lightning/modal';
import MaskingExportModal from 'c/maskingExportModal';

// Mock utilityLogger so the copy path (via c/utilitySystem.copyToClipBoard) never reaches the real
// module-singleton logger or its Apex persistence stub.
jest.mock('c/utilityLogger', () =>
{
	return {
		__esModule: true, default: {
			debug: jest.fn(), info: jest.fn(), warn: jest.fn(), error: jest.fn()
		}
	};
}, {virtual: true});

jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Title', () => ({default: 'Export masking package'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Download', () => ({default: 'Download package'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Cancel', () => ({default: 'Close'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_ChangeSummary_Singular',
		() => ({default: 'This package applies 1 change to {0} when deployed ({1} add · {2} disable · {3} re-enable). Nothing changes in your org until you deploy it.'}),
		{virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_ChangeSummary_Plural',
		() => ({default: 'This package applies {0} changes to {1} when deployed ({2} add · {3} disable · {4} re-enable). Nothing changes in your org until you deploy it.'}),
		{virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_PackageHeading', () => ({default: 'In this package ({0})'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_NoChanges', () => ({default: 'No changes.'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Verb_Add', () => ({default: 'add'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Verb_Disable', () => ({default: 'disable'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Verb_ReEnable', () => ({default: 're-enable'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_ObjectWideTag', () => ({default: 'object-wide'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Deploy_CliIntro',
		() => ({default: 'Salesforce CLI (fastest): set your org alias, copy the command, and run it from the unzipped folder.'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Deploy_OtherToolsNote',
		() => ({default: 'Your own tools: import the package with a change set, Workbench, or your CI/CD pipeline.'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Deploy_Command', () => ({default: 'sf project deploy start --metadata-dir metadata -o {0}'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Deploy_AliasPlaceholder', () => ({default: '<your-org-alias>'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_OrgAlias_Label', () => ({default: 'Org alias'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_OrgAlias_Placeholder', () => ({default: 'MyOrg'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Deploy_CommandAriaLabel', () => ({default: 'Deploy command'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Copy', () => ({default: 'Copy command'}), {virtual: true});
jest.mock('@salesforce/label/c.DataMaskingAdvisor_ExportModal_Copied', () => ({default: 'Copied'}), {virtual: true});

/**
 * @description Mounts a maskingExportModal with the supplied properties and returns the element. The three
 *              diff groups default to a representative add (field), re-enable (field), and disable
 *              (object-wide) so the contents list and summary exercise every branch unless overridden.
 * @param {Object} [props] - @api property overrides applied before append.
 * @returns {HTMLElement}
 */
function createModal(props = {})
{
	const element = createElement('c-masking-export-modal', {is: MaskingExportModal});
	element.objectApiName = props.objectApiName === undefined ? 'Account' : props.objectApiName;
	element.addRows = props.addRows === undefined ? [{scope: 'F', fieldLabel: 'Email', ruleLabel: 'Mask Generic'}] : props.addRows;
	element.reEnableRows = props.reEnableRows === undefined ? [{scope: 'F', fieldLabel: 'SSN', ruleLabel: 'Mask Street'}] : props.reEnableRows;
	element.disableRows = props.disableRows === undefined ? [{scope: 'O', fieldLabel: '', ruleLabel: 'Mask Credit Card'}] : props.disableRows;
	if(props.fileName !== undefined)
	{
		element.fileName = props.fileName;
	}
	document.body.appendChild(element);
	return element;
}

/**
 * @description Flushes the LWC microtask render queue.
 * @returns {Promise<void>}
 */
function flush()
{
	return Promise.resolve();
}

/**
 * @description Settles the asynchronous copy path (clipboard promise, fallback, then re-render) by
 *              draining the macrotask queue once, which lets every queued microtask run first.
 * @returns {Promise<void>}
 */
function settle()
{
	return new Promise((resolve) => setTimeout(resolve, 0));
}

/**
 * @description Reads the trimmed text content of the first node matching the test id.
 * @param {HTMLElement} element - The mounted modal.
 * @param {string} testId - The data-testid to query.
 * @returns {string|null}
 */
function textOf(element, testId)
{
	const node = element.shadowRoot.querySelector(`[data-testid="${testId}"]`);
	return node ? node.textContent : null;
}

afterEach(() =>
{
	while(document.body.firstChild)
	{
		document.body.removeChild(document.body.firstChild);
	}
	jest.clearAllMocks();
});

describe('c-masking-export-modal', () =>
{
	describe('change summary', () =>
	{
		it('renders the plural summary with the total, object, and add/disable/re-enable breakdown', async() =>
		{
			const element = createModal();
			await flush();

			expect(textOf(element, 'change-summary'))
			.toBe('This package applies 3 changes to Account when deployed (1 add · 1 disable · 1 re-enable). Nothing changes in your org until you deploy it.');
		});

		it('renders the singular summary when the diff carries exactly one change', async() =>
		{
			const element = createModal({addRows: [{scope: 'F', fieldLabel: 'Email', ruleLabel: 'Mask Generic'}], reEnableRows: [], disableRows: []});
			await flush();

			expect(textOf(element, 'change-summary'))
			.toBe('This package applies 1 change to Account when deployed (1 add · 0 disable · 0 re-enable). Nothing changes in your org until you deploy it.');
		});

		it('heads the contents list with the total change count', async() =>
		{
			const element = createModal();
			await flush();
			expect(textOf(element, 'package-heading')).toBe('In this package (3)');
		});
	});

	describe('package contents grouping', () =>
	{
		it('lists each change under its verb group with the correct verb tag', async() =>
		{
			const element = createModal();
			await flush();

			const rows = element.shadowRoot.querySelectorAll('[data-testid="package-row"]');
			expect(rows).toHaveLength(3);
			// Order is Add, then Re-enable, then Disable.
			expect(rows[0].dataset.verb).toBe('add');
			expect(rows[1].dataset.verb).toBe('re-enable');
			expect(rows[2].dataset.verb).toBe('disable');
			expect(rows[0].querySelector('[data-testid="package-row-verb"]').textContent).toBe('add');
			expect(rows[2].querySelector('[data-testid="package-row-verb"]').textContent).toBe('disable');
		});

		it('renders a field row as field → rule and an object-wide row as rule + object-wide tag', async() =>
		{
			const element = createModal();
			await flush();

			const rows = element.shadowRoot.querySelectorAll('[data-testid="package-row"]');
			const fieldMain = rows[0].querySelector('[data-testid="package-row-main"]').textContent;
			expect(fieldMain).toContain('Email');
			expect(fieldMain).toContain('Mask Generic');
			expect(fieldMain).not.toContain('object-wide');

			const objectWideMain = rows[2].querySelector('[data-testid="package-row-main"]').textContent;
			expect(objectWideMain).toContain('Mask Credit Card');
			expect(objectWideMain).toContain('object-wide');
		});

		it('renders the empty-state row when the diff is empty', async() =>
		{
			const element = createModal({addRows: [], reEnableRows: [], disableRows: []});
			await flush();

			expect(element.shadowRoot.querySelectorAll('[data-testid="package-row"]')).toHaveLength(0);
			expect(textOf(element, 'package-row-empty')).toBe('No changes.');
			expect(textOf(element, 'package-heading')).toBe('In this package (0)');
		});

		it('degrades to an empty package when no diff groups are supplied at all', async() =>
		{
			// The reusable modal must tolerate being opened without the three @api group arrays — its counts
			// and contents fall back to empty rather than throwing.
			const element = createElement('c-masking-export-modal', {is: MaskingExportModal});
			element.objectApiName = 'Account';
			document.body.appendChild(element);
			await flush();

			expect(element.shadowRoot.querySelectorAll('[data-testid="package-row"]')).toHaveLength(0);
			expect(textOf(element, 'package-row-empty')).toBe('No changes.');
			expect(textOf(element, 'package-heading')).toBe('In this package (0)');
		});

		it('renders the supplied group and skips absent ones when only some groups are passed', async() =>
		{
			// Only the create group is supplied — the contents list still builds, with the absent disable and
			// re-enable groups falling back to empty.
			const element = createElement('c-masking-export-modal', {is: MaskingExportModal});
			element.objectApiName = 'Account';
			element.addRows = [{scope: 'F', fieldLabel: 'Email', ruleLabel: 'Mask Generic'}];
			document.body.appendChild(element);
			await flush();

			const rows = element.shadowRoot.querySelectorAll('[data-testid="package-row"]');
			expect(rows).toHaveLength(1);
			expect(rows[0].dataset.verb).toBe('add');
		});
	});

	describe('deploy paths', () =>
	{
		it('shows the alias placeholder in the command before any alias is typed', async() =>
		{
			const element = createModal();
			await flush();
			expect(textOf(element, 'deploy-command')).toBe('sf project deploy start --metadata-dir metadata -o <your-org-alias>');
		});

		it('fills the typed org alias into the displayed deploy command', async() =>
		{
			const element = createModal();
			await flush();

			const input = element.shadowRoot.querySelector('[data-testid="alias-input"]');
			input.dispatchEvent(new CustomEvent('change', {detail: {value: 'AcmeProd'}}));
			await flush();

			expect(textOf(element, 'deploy-command')).toBe('sf project deploy start --metadata-dir metadata -o AcmeProd');
		});

		it('falls back to the placeholder when the alias is cleared to whitespace', async() =>
		{
			const element = createModal();
			await flush();

			const input = element.shadowRoot.querySelector('[data-testid="alias-input"]');
			input.dispatchEvent(new CustomEvent('change', {detail: {value: '   '}}));
			await flush();

			expect(textOf(element, 'deploy-command')).toBe('sf project deploy start --metadata-dir metadata -o <your-org-alias>');
		});

		it('copies the resolved command to the clipboard and flips the button label', async() =>
		{
			const writeText = jest.fn();
			Object.defineProperty(navigator, 'clipboard', {value: {writeText}, configurable: true});
			const element = createModal();
			await flush();

			const input = element.shadowRoot.querySelector('[data-testid="alias-input"]');
			input.dispatchEvent(new CustomEvent('change', {detail: {value: 'AcmeProd'}}));
			await flush();
			element.shadowRoot.querySelector('[data-testid="copy-command-button"]').click();
			await settle();

			expect(writeText).toHaveBeenCalledWith('sf project deploy start --metadata-dir metadata -o AcmeProd');
			expect(textOf(element, 'copy-command-button')).toBe('Copied');
		});

		it('does not claim Copied when the clipboard write fails', async() =>
		{
			const writeText = jest.fn().mockRejectedValue(new Error('Write denied'));
			Object.defineProperty(navigator, 'clipboard', {value: {writeText}, configurable: true});
			// The temporary-input fallback also fails, so the copy never happened.
			// noinspection JSDeprecatedSymbols
			document.execCommand = jest.fn().mockReturnValue(false);
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="copy-command-button"]').click();
			await settle();

			expect(textOf(element, 'copy-command-button')).toBe('Copy command');
		});

		it('does not claim Copied when the clipboard API is unavailable and the fallback fails', async() =>
		{
			Object.defineProperty(navigator, 'clipboard', {value: undefined, configurable: true});
			// noinspection JSDeprecatedSymbols
			document.execCommand = jest.fn().mockReturnValue(false);
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="copy-command-button"]').click();
			await settle();

			expect(textOf(element, 'copy-command-button')).toBe('Copy command');
		});

		it('flips to Copied when the restricted-context fallback copy succeeds', async() =>
		{
			Object.defineProperty(navigator, 'clipboard', {value: undefined, configurable: true});
			// noinspection JSDeprecatedSymbols
			document.execCommand = jest.fn().mockReturnValue(true);
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="copy-command-button"]').click();
			await settle();

			expect(textOf(element, 'copy-command-button')).toBe('Copied');
		});

		it('re-arms the copy button label after the alias changes', async() =>
		{
			const writeText = jest.fn();
			Object.defineProperty(navigator, 'clipboard', {value: {writeText}, configurable: true});
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="copy-command-button"]').click();
			await settle();
			expect(textOf(element, 'copy-command-button')).toBe('Copied');

			const input = element.shadowRoot.querySelector('[data-testid="alias-input"]');
			input.dispatchEvent(new CustomEvent('change', {detail: {value: 'Other'}}));
			await flush();

			expect(textOf(element, 'copy-command-button')).toBe('Copy command');
		});

		it('renders both the CLI intro and the other-tools note', async() =>
		{
			const element = createModal();
			await flush();
			expect(textOf(element, 'deploy-a-intro')).toContain('Salesforce CLI');
			expect(textOf(element, 'deploy-b-note')).toContain('change set');
		});
	});

	describe('package name chip', () =>
	{
		it('renders the package file name when one is supplied', async() =>
		{
			const element = createModal({fileName: 'masking-configuration.zip'});
			await flush();
			expect(textOf(element, 'package-name')).toBe('masking-configuration.zip');
		});

		it('omits the package chip when no file name is supplied', async() =>
		{
			const element = createModal();
			await flush();
			expect(element.shadowRoot.querySelector('[data-testid="package-name"]')).toBeNull();
		});

		it('omits the package chip when the file name is blank', async() =>
		{
			const element = createModal({fileName: '   '});
			await flush();
			expect(element.shadowRoot.querySelector('[data-testid="package-name"]')).toBeNull();
		});
	});

	describe('resolution', () =>
	{
		it('resolves {action:"download"} on Download', async() =>
		{
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="download-button"]').click();

			expect(mockClose).toHaveBeenCalledTimes(1);
			expect(mockClose).toHaveBeenCalledWith({action: 'download'});
		});

		it('resolves null on Close', async() =>
		{
			const element = createModal();
			await flush();

			element.shadowRoot.querySelector('[data-testid="cancel-button"]').click();

			expect(mockClose).toHaveBeenCalledTimes(1);
			expect(mockClose).toHaveBeenCalledWith(null);
		});
	});

	describe('chrome', () =>
	{
		it('renders the modal header with the title and both action buttons', async() =>
		{
			const element = createModal();
			await flush();

			expect(element.shadowRoot.querySelector('lightning-modal-header').label).toBe('Export masking package');
			expect(element.shadowRoot.querySelector('[data-testid="download-button"]')).not.toBeNull();
			expect(element.shadowRoot.querySelector('[data-testid="cancel-button"]')).not.toBeNull();
		});
	});
});
